Add custom two,three and four terminal devics
mabrains/gdsfactory-generic_pdk pull request #11
Opened 2024-01-17 18:23 UTC by RehabSayed-G

…h doped_heater

2024-01-30 11:01 UTC, RehabSayed-G commented
@FaragElsayed2 , 
Ready For Review for the following devices : 
* straight_heater_metal
* straight_heater_metal_undercut
* mzi_mmi
* mmi1x2
* mmi2x2
* mmi_90_degree_hybrid

2024-01-31 15:42 UTC, FaragElsayed2 commented on klayout/lvs/rule_decks/general_derivations.lvs
> +wg_con = wg.not(heater_mk).not(heater_length_mk).not(mmi_mk).not(mmi_length_mk).not(mzi_len_mk)
Add a new exclusion layer then use it, for optimization purpose

```
wg_con_exclude = heater_mk.join(heater_length_mk).join(mmi_mk).join(mmi_length_mk).join(mzi_len_mk)

wg_con = wg.not(wg_con_exclude)
```

2024-01-31 15:45 UTC, FaragElsayed2 commented on klayout/lvs/rule_decks/heater_extraction.lvs
> +# # ====================
To be modified as we agreed for other devices [Using custom class - N term]

2024-01-31 15:46 UTC, FaragElsayed2 commented on klayout/lvs/rule_decks/heater_extraction.lvs
> +# # --- HEATER DOPED ---
To be modified as we agreed for other devices [Using custom class - N term]

2024-01-31 15:47 UTC, FaragElsayed2 commented on klayout/lvs/testing/testcases/unit/heater_devices/netlist/straight_heater_doped/straight_heater_doped_rib.spice
Please add Licence for all netlists.

2024-01-31 15:50 UTC, FaragElsayed2 commented on klayout/lvs/rule_decks/custom_classes.lvs
> +      super("#{sup} lx=0 ly=0 dl=0", element)
We don't have any `Z` or `R` devices, could you check this?

2024-01-31 15:50 UTC, FaragElsayed2 commented on klayout/lvs/rule_decks/custom_classes.lvs
> +      super("#{sup} R=0", element)
Same as above

2024-01-31 15:52 UTC, FaragElsayed2 commented on klayout/lvs/rule_decks/custom_classes.lvs
> +        if model.include?('MMI1X2')
Why is this specific for `mmi1x2`? it could be used for all `mmi` types.

2024-01-31 15:54 UTC, FaragElsayed2 commented on klayout/lvs/rule_decks/custom_classes.lvs
> +        if model.include?('MMI1X2')
You could combine the following checks outside `nets.size` check.

```
if model.include?('MMI1X2')
if model.include?('MMI2X2')
if model.include?('MMI_90DEGREE')
```

2024-01-31 15:56 UTC, FaragElsayed2 commented on klayout/lvs/rule_decks/custom_classes.lvs
> +        unless cls
Device creation could be done only one time outside the `nets.size` check for all conditions.

2024-01-31 15:58 UTC, FaragElsayed2 commented on klayout/lvs/rule_decks/custom_classes.lvs
>  class NResistor < RBA::DeviceClassResistor
I believe we couldn't use this anymore.

2024-01-31 15:59 UTC, FaragElsayed2 commented on klayout/lvs/rule_decks/custom_classes.lvs
> +class DeviceClassNTerminal < RBA::DeviceClassResistor
Could you please split all custom devices in new lvs file, then include it in this file or in the main one?

2024-01-31 16:00 UTC, FaragElsayed2 commented on klayout/lvs/rule_decks/custom_classes.lvs
Please make sure to add comments in this file to explain your steps. Also please remove any code comments.

2024-01-31 16:01 UTC, FaragElsayed2 requested changes
Please check required changes @RehabSayed-G

2024-02-04 18:15 UTC, RehabSayed-G commented
@FaragElsayed2 , Ready for review

2024-02-05 07:45 UTC, FaragElsayed2 approved these changes

2024-02-05 07:45 UTC, merged